### datasources

In [1]:
import pandas as pd
import seaborn as sns
%run plotfuncs

In [4]:
dir = './corn_climate_risk_futures_daily_master.csv'
riskfutures = pd.read_csv(dir)

In [3]:
harvestperiodorder = {
            'Off-season': 0,\
            'Planting': 1,\
            'Mid-season': 2,\
            'Harvest': 3,\
            'Peak Harvest': 4
        }
## order according to https://extension.usu.edu/vegetableguide/sweet-corn/harvest-handling

### EDA - Climate Risk and Corn Futures Data

In [5]:
riskfutures.info(verbose=True)
## Helios data doc:"Futures data may have gaps on non-trading days (weekends, holidays)"

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 320661 entries, 0 to 320660
Data columns (total 41 columns):
 #   Column                                                    Non-Null Count   Dtype
---  ------                                                    --------------   -----
 0   ID                                                        320661 non-null  object
 1   crop_name                                                 320661 non-null  object
 2   country_name                                              320661 non-null  object
 3   country_code                                              320661 non-null  object
 4   region_name                                               320661 non-null  object
 5   region_id                                                 320661 non-null  object
 6   harvest_period                                            320661 non-null  object
 7   growing_season_year                                       320661 non-null  int64
 8   date_on                                                   320661 non-null  object
 9   climate_risk_cnt_locations_heat_stress_risk_low           320661 non-null  int64
 10  climate_risk_cnt_locations_heat_stress_risk_medium        320661 non-null  int64
 11  climate_risk_cnt_locations_heat_stress_risk_high          320661 non-null  int64
 12  climate_risk_cnt_locations_unseasonably_cold_risk_low     320661 non-null  int64
 13  climate_risk_cnt_locations_unseasonably_cold_risk_medium  320661 non-null  int64
 14  climate_risk_cnt_locations_unseasonably_cold_risk_high    320661 non-null  int64
 15  climate_risk_cnt_locations_excess_precip_risk_low         320661 non-null  int64
 16  climate_risk_cnt_locations_excess_precip_risk_medium      320661 non-null  int64
 17  climate_risk_cnt_locations_excess_precip_risk_high        320661 non-null  int64
 18  climate_risk_cnt_locations_drought_risk_low               320661 non-null  int64
 19  climate_risk_cnt_locations_drought_risk_medium            320661 non-null  int64
 20  climate_risk_cnt_locations_drought_risk_high              320661 non-null  int64
 21  futures_close_ZC_1                                        219531 non-null  float64
 22  futures_close_ZC_2                                        219531 non-null  float64
 23  futures_close_ZW_1                                        219531 non-null  float64
 24  futures_close_ZS_1                                        219531 non-null  float64
 25  futures_zc1_ret_pct                                       219531 non-null  float64
 26  futures_zc1_ret_log                                       219531 non-null  float64
 27  futures_zc_term_spread                                    219531 non-null  float64
 28  futures_zc_term_ratio                                     219531 non-null  float64
 29  futures_zc1_ma_20                                         219531 non-null  float64
 30  futures_zc1_ma_60                                         219531 non-null  float64
 31  futures_zc1_ma_120                                        219531 non-null  float64
 32  futures_zc1_vol_20                                        219531 non-null  float64
 33  futures_zc1_vol_60                                        219531 non-null  float64
 34  futures_zw_zc_spread                                      219531 non-null  float64
 35  futures_zc_zw_ratio                                       219531 non-null  float64
 36  futures_zs_zc_spread                                      219531 non-null  float64
 37  futures_zc_zs_ratio                                       219531 non-null  float64
 38  date_on_year                                              320661 non-null  int64
 39  date_on_month                                             320661 non-null  int64
 40  date_on_year_month                                        320661 non-null  object
dtypes: float64(17), int64(15), object(9)
memory usage: 100.3+ MB

In [16]:
riskfutures.head(3)

,ID,crop_name,country_name,country_code,region_name,region_id,harvest_period,growing_season_year,date_on,climate_risk_cnt_locations_heat_stress_risk_low,...,futures_zc1_ma_120,futures_zc1_vol_20,futures_zc1_vol_60,futures_zw_zc_spread,futures_zc_zw_ratio,futures_zs_zc_spread,futures_zc_zs_ratio,date_on_year,date_on_month,date_on_year_month
0,8af42722-3f05-4ede-80fc-605e0e2b3b67,Corn: Commodity Tracked,Argentina,AR,Buenos Aires,bffad37a-7c60-432f-984a-8ea83a944311,Harvest,2017,2016-06-15,23,...,375.014583,0.013520,0.015724,48.50,0.898429,727.00,0.371107,2016,6,2016_06
1,54f4ddc5-e7ab-4bfb-ad6a-5649841af563,Corn: Commodity Tracked,Argentina,AR,Buenos Aires,bffad37a-7c60-432f-984a-8ea83a944311,Harvest,2017,2016-06-16,23,...,375.512500,0.013799,0.015792,47.25,0.900000,709.25,0.374835,2016,6,2016_06
2,63a41fce-d371-4295-a58a-dc6491664020,Corn: Commodity Tracked,Argentina,AR,Buenos Aires,bffad37a-7c60-432f-984a-8ea83a944311,Harvest,2017,2016-06-17,23,...,376.122917,0.013442,0.016145,43.50,0.909610,721.75,0.377533,2016,6,2016_06

In [17]:
riskfutures.describe(include='object')

,ID,crop_name,country_name,country_code,region_name,region_id,harvest_period,date_on,date_on_year_month
count,320661,320661,320661,320661,320661,320661,320661,320661,320661
unique,320661,1,11,11,89,89,5,3637,120
top,8af42722-3f05-4ede-80fc-605e0e2b3b67,Corn: Commodity Tracked,Russia,RU,Kabardino-Balkaria,3614b209-e1df-453d-9fec-16b532706c1e,Off-season,2021-01-25,2021_01
freq,1,320661,90875,90875,3635,3635,96408,89,2759

### corn risk and futures price data time range is from 2016-01 to 2025-12 in 11 countries and 89 subregions.  
### EU as a country and its six subregions are missing compared to regional market share data

## EDA 1.2: corn futures data

In [8]:
cornfutures = riskfutures.iloc[:,[8,38,39,40]+list(range(21,38))]

In [9]:
cornfutures.head(3)

,date_on,date_on_year,date_on_month,date_on_year_month,futures_close_ZC_1,futures_close_ZC_2,futures_close_ZW_1,futures_close_ZS_1,futures_zc1_ret_pct,futures_zc1_ret_log,...,futures_zc_term_ratio,futures_zc1_ma_20,futures_zc1_ma_60,futures_zc1_ma_120,futures_zc1_vol_20,futures_zc1_vol_60,futures_zw_zc_spread,futures_zc_zw_ratio,futures_zs_zc_spread,futures_zc_zs_ratio
0,2016-06-15,2016,6,2016_06,429.00,434.00,477.50,1156.0,-0.017182,-0.017331,...,1.011655,414.4125,387.695833,375.014583,0.013520,0.015724,48.50,0.898429,727.00,0.371107
1,2016-06-16,2016,6,2016_06,425.25,430.50,472.50,1134.5,-0.008741,-0.008780,...,1.012346,415.7000,388.616667,375.512500,0.013799,0.015792,47.25,0.900000,709.25,0.374835
2,2016-06-17,2016,6,2016_06,437.75,442.75,481.25,1159.5,0.029394,0.028971,...,1.011422,418.0875,389.770833,376.122917,0.013442,0.016145,43.50,0.909610,721.75,0.377533

In [15]:
cornfutures.iloc[:,4:].describe()

,futures_close_ZC_1,futures_close_ZC_2,futures_close_ZW_1,futures_close_ZS_1,futures_zc1_ret_pct,futures_zc1_ret_log,futures_zc_term_spread,futures_zc_term_ratio,futures_zc1_ma_20,futures_zc1_ma_60,futures_zc1_ma_120,futures_zc1_vol_20,futures_zc1_vol_60,futures_zw_zc_spread,futures_zc_zw_ratio,futures_zs_zc_spread,futures_zc_zs_ratio
count,219531.000000,219531.000000,219531.000000,219531.000000,219531.000000,219531.000000,219531.000000,219531.000000,219531.000000,219531.000000,219531.000000,219531.000000,219531.000000,219531.000000,219531.000000,219531.000000,219531.000000
mean,454.127871,456.351492,578.048551,1123.107332,0.000199,0.000067,2.223621,1.010926,453.874548,453.421769,453.034423,0.014576,0.015067,123.920680,0.787401,668.979461,0.402297
std,121.263457,110.404797,148.799052,240.295615,0.016143,0.016336,21.298437,0.036084,120.412401,118.692795,115.980842,0.006966,0.005816,65.799846,0.083645,135.966666,0.040228
min,301.500000,312.000000,361.000000,791.000000,-0.182432,-0.201422,-145.000000,0.804688,314.075000,321.850000,327.258333,0.004435,0.006106,-61.250000,0.525697,425.500000,0.302032
25%,365.250000,373.500000,481.750000,932.500000,-0.008269,-0.008304,2.750000,1.006085,365.275000,365.387500,366.235417,0.010209,0.011541,79.750000,0.728104,550.000000,0.368485
50%,406.750000,417.750000,537.750000,1027.750000,0.000539,0.000538,8.000000,1.020445,406.575000,400.066667,396.872917,0.013117,0.013566,112.750000,0.789177,641.250000,0.401733
75%,525.500000,515.250000,635.000000,1320.000000,0.008671,0.008633,11.750000,1.029010,525.412500,534.275000,535.997917,0.016508,0.016490,161.000000,0.840793,774.000000,0.429182
max,818.250000,813.500000,1425.250000,1769.000000,0.079582,0.076574,26.000000,1.069815,803.187500,778.750000,739.733333,0.049164,0.038107,676.000000,1.093014,1080.250000,0.510756